name: Checks

on:
  push:
    branches:
    - 'master'
  pull_request:


jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - uses: astral-sh/setup-uv@v5
    - name: Test
      run: |
        uv sync --group dev
        uv run python -m unittest discover tests/

  check:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: astral-sh/setup-uv@v5
    - name: Unit tests for coverage
      run: |
        uv sync --group dev
        uv run coverage run -m unittest discover tests
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Unit Test
    - name: Lint with flake8
      run: uv run python -m flake8 ./src/janome
    - name: Lint with mypy
      run: uv run python -m mypy ./src/janome

  coveralls_finish:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
